// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VaccineNotifierApp.Data;

namespace VaccineNotifierApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210528034008_AddedNotifyMeCol")]
    partial class AddedNotifyMeCol
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VaccineNotifierApp.Data.Models.VaccineSlotNotifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NotifyMe")
                        .HasColumnType("bit");

                    b.Property<bool>("Subscribe18PlusNotifier")
                        .HasColumnType("bit");

                    b.Property<bool>("Subscribe45PlusNotifier")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("VaccineSlotNotifiers");
                });
#pragma warning restore 612, 618
        }
    }
}
